# syntax=docker/dockerfile:1.7

FROM gcr.io/distroless/static-debian12:nonroot
ARG TARGETARCH
WORKDIR /
COPY dist/linux-${TARGETARCH}/recomma /usr/local/bin/recomma
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/recomma"]
