# syntax=docker/dockerfile:1.7

ARG TARGETARCH

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /
COPY dist/linux-${TARGETARCH}/recomma /usr/local/bin/recomma
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/recomma"]
