//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	externalRef0 "github.com/terwey/3commas-sdk-go/threecommas"
)

// Defines values for OrderLogEntryType.
const (
	HyperliquidStatus     OrderLogEntryType = "hyperliquid_status"
	HyperliquidSubmission OrderLogEntryType = "hyperliquid_submission"
	ThreeCommasEvent      OrderLogEntryType = "three_commas_event"
)

// BotRecord defines model for BotRecord.
type BotRecord struct {
	BotId        int64            `json:"bot_id"`
	LastSyncedAt time.Time        `json:"last_synced_at"`
	Payload      externalRef0.Bot `json:"payload"`
}

// DealRecord defines model for DealRecord.
type DealRecord struct {
	BotId     int64     `json:"bot_id"`
	CreatedAt time.Time `json:"created_at"`
	DealId    int64     `json:"deal_id"`

	// Payload A single DCA‐bot deal, with all its execution and P/L details.
	Payload   externalRef0.Deal `json:"payload"`
	UpdatedAt time.Time         `json:"updated_at"`
}

// OrderLogEntry defines model for OrderLogEntry.
type OrderLogEntry struct {
	// BotEventId Bot-event ID when available (present for 3Commas rows).
	BotEventId  *int64    `json:"bot_event_id"`
	MetadataHex string    `json:"metadata_hex"`
	ObservedAt  time.Time `json:"observed_at"`

	// Payload Raw JSON payload from the corresponding table.
	Payload map[string]interface{} `json:"payload"`
	Type    OrderLogEntryType      `json:"type"`
}

// OrderLogEntryType defines model for OrderLogEntry.Type.
type OrderLogEntryType string

// OrderRecord defines model for OrderRecord.
type OrderRecord struct {
	BotEventId int64 `json:"bot_event_id"`

	// BotEventPayload Raw payload from `threecommas_botevents`.
	BotEventPayload map[string]interface{} `json:"bot_event_payload"`
	BotId           int64                  `json:"bot_id"`
	CreatedAt       time.Time              `json:"created_at"`
	DealId          int64                  `json:"deal_id"`

	// LatestStatus Raw JSON from the most recent `hyperliquid_status_history` row for this metadata.
	LatestStatus *map[string]interface{} `json:"latest_status"`

	// LatestSubmission Raw JSON from `hyperliquid_submissions` for this metadata (last write wins).
	LatestSubmission *map[string]interface{} `json:"latest_submission"`

	// LogEntries Present only when `include_log=true`. Entries are filtered to the same metadata/time window.
	LogEntries  *[]OrderLogEntry `json:"log_entries"`
	MetadataHex string           `json:"metadata_hex"`
	ObservedAt  time.Time        `json:"observed_at"`
}

// ListBotsParams defines parameters for ListBots.
type ListBotsParams struct {
	// BotId Return only the bot with this ID (exact match).
	BotId *int64 `form:"bot_id,omitempty" json:"bot_id,omitempty"`

	// UpdatedFrom ISO-8601 timestamp; include bots touched at or after this time.
	UpdatedFrom *time.Time `form:"updated_from,omitempty" json:"updated_from,omitempty"`

	// UpdatedTo ISO-8601 timestamp; include bots touched at or before this time.
	UpdatedTo *time.Time `form:"updated_to,omitempty" json:"updated_to,omitempty"`

	// Limit Maximum number of rows (default 100, max 500).
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// PageToken Opaque cursor returned by a previous call (empty for first page).
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListDealsParams defines parameters for ListDeals.
type ListDealsParams struct {
	// DealId Return only the deal with this ID (exact match).
	DealId *int64 `form:"deal_id,omitempty" json:"deal_id,omitempty"`

	// BotId Restrict to deals belonging to this bot.
	BotId *int64 `form:"bot_id,omitempty" json:"bot_id,omitempty"`

	// UpdatedFrom ISO-8601 timestamp; include deals updated at or after this time.
	UpdatedFrom *time.Time `form:"updated_from,omitempty" json:"updated_from,omitempty"`

	// UpdatedTo ISO-8601 timestamp; include deals updated at or before this time.
	UpdatedTo *time.Time `form:"updated_to,omitempty" json:"updated_to,omitempty"`

	// Limit Maximum number of rows (default 100, max 500).
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// PageToken Opaque cursor returned by a previous call.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	// Metadata Case-insensitive prefix match on metadata hex; exact match recommended for drill-down.
	Metadata *string `form:"metadata,omitempty" json:"metadata,omitempty"`

	// BotId Restrict to events emitted by this bot ID.
	BotId *int64 `form:"bot_id,omitempty" json:"bot_id,omitempty"`

	// DealId Restrict to events emitted by this deal ID.
	DealId *int64 `form:"deal_id,omitempty" json:"deal_id,omitempty"`

	// BotEventId Restrict to a specific 3Commas bot-event ID (exact match).
	BotEventId *int64 `form:"bot_event_id,omitempty" json:"bot_event_id,omitempty"`

	// ObservedFrom ISO-8601 timestamp; include events observed at or after this time.
	ObservedFrom *time.Time `form:"observed_from,omitempty" json:"observed_from,omitempty"`

	// ObservedTo ISO-8601 timestamp; include events observed at or before this time.
	ObservedTo *time.Time `form:"observed_to,omitempty" json:"observed_to,omitempty"`

	// IncludeLog When true, embed `log_entries` for each order, limited to the same metadata and time range (default false).
	IncludeLog *bool `form:"include_log,omitempty" json:"include_log,omitempty"`

	// Limit Maximum number of rows (default 100, max 500).
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// PageToken Opaque cursor returned by a previous call.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// StreamOrdersParams defines parameters for StreamOrders.
type StreamOrdersParams struct {
	// Metadata Case-insensitive prefix match; only events for matching metadata are emitted.
	Metadata *string `form:"metadata,omitempty" json:"metadata,omitempty"`

	// BotId Restrict to this bot ID.
	BotId *int64 `form:"bot_id,omitempty" json:"bot_id,omitempty"`

	// DealId Restrict to this deal ID.
	DealId *int64 `form:"deal_id,omitempty" json:"deal_id,omitempty"`

	// BotEventId Restrict to this bot-event ID.
	BotEventId *int64 `form:"bot_event_id,omitempty" json:"bot_event_id,omitempty"`

	// ObservedFrom If supplied, drop events older than this timestamp (useful for resume).
	ObservedFrom *time.Time `form:"observed_from,omitempty" json:"observed_from,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List cached 3Commas bots
	// (GET /api/bots)
	ListBots(w http.ResponseWriter, r *http.Request, params ListBotsParams)
	// List cached 3Commas deals
	// (GET /api/deals)
	ListDeals(w http.ResponseWriter, r *http.Request, params ListDealsParams)
	// List acted-on bot events with Hyperliquid context
	// (GET /api/orders)
	ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams)
	// Stream live changes to acted-on orders
	// (GET /sse/orders)
	StreamOrders(w http.ResponseWriter, r *http.Request, params StreamOrdersParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBots operation middleware
func (siw *ServerInterfaceWrapper) ListBots(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBotsParams

	// ------------- Optional query parameter "bot_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "bot_id", r.URL.Query(), &params.BotId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bot_id", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "updated_from", r.URL.Query(), &params.UpdatedFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_from", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "updated_to", r.URL.Query(), &params.UpdatedTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_to", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBots(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeals operation middleware
func (siw *ServerInterfaceWrapper) ListDeals(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDealsParams

	// ------------- Optional query parameter "deal_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "deal_id", r.URL.Query(), &params.DealId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deal_id", Err: err})
		return
	}

	// ------------- Optional query parameter "bot_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "bot_id", r.URL.Query(), &params.BotId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bot_id", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "updated_from", r.URL.Query(), &params.UpdatedFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_from", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "updated_to", r.URL.Query(), &params.UpdatedTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_to", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeals(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrdersParams

	// ------------- Optional query parameter "metadata" -------------

	err = runtime.BindQueryParameter("form", true, false, "metadata", r.URL.Query(), &params.Metadata)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metadata", Err: err})
		return
	}

	// ------------- Optional query parameter "bot_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "bot_id", r.URL.Query(), &params.BotId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bot_id", Err: err})
		return
	}

	// ------------- Optional query parameter "deal_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "deal_id", r.URL.Query(), &params.DealId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deal_id", Err: err})
		return
	}

	// ------------- Optional query parameter "bot_event_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "bot_event_id", r.URL.Query(), &params.BotEventId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bot_event_id", Err: err})
		return
	}

	// ------------- Optional query parameter "observed_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "observed_from", r.URL.Query(), &params.ObservedFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "observed_from", Err: err})
		return
	}

	// ------------- Optional query parameter "observed_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "observed_to", r.URL.Query(), &params.ObservedTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "observed_to", Err: err})
		return
	}

	// ------------- Optional query parameter "include_log" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_log", r.URL.Query(), &params.IncludeLog)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_log", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamOrders operation middleware
func (siw *ServerInterfaceWrapper) StreamOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamOrdersParams

	// ------------- Optional query parameter "metadata" -------------

	err = runtime.BindQueryParameter("form", true, false, "metadata", r.URL.Query(), &params.Metadata)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metadata", Err: err})
		return
	}

	// ------------- Optional query parameter "bot_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "bot_id", r.URL.Query(), &params.BotId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bot_id", Err: err})
		return
	}

	// ------------- Optional query parameter "deal_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "deal_id", r.URL.Query(), &params.DealId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deal_id", Err: err})
		return
	}

	// ------------- Optional query parameter "bot_event_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "bot_event_id", r.URL.Query(), &params.BotEventId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bot_event_id", Err: err})
		return
	}

	// ------------- Optional query parameter "observed_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "observed_from", r.URL.Query(), &params.ObservedFrom)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "observed_from", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/bots", wrapper.ListBots)
	m.HandleFunc("GET "+options.BaseURL+"/api/deals", wrapper.ListDeals)
	m.HandleFunc("GET "+options.BaseURL+"/api/orders", wrapper.ListOrders)
	m.HandleFunc("GET "+options.BaseURL+"/sse/orders", wrapper.StreamOrders)

	return m
}

type ListBotsRequestObject struct {
	Params ListBotsParams
}

type ListBotsResponseObject interface {
	VisitListBotsResponse(w http.ResponseWriter) error
}

type ListBots200JSONResponse struct {
	Items         []BotRecord `json:"items"`
	NextPageToken *string     `json:"next_page_token"`
}

func (response ListBots200JSONResponse) VisitListBotsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListBots400Response struct {
}

func (response ListBots400Response) VisitListBotsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ListBots500Response struct {
}

func (response ListBots500Response) VisitListBotsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type ListDealsRequestObject struct {
	Params ListDealsParams
}

type ListDealsResponseObject interface {
	VisitListDealsResponse(w http.ResponseWriter) error
}

type ListDeals200JSONResponse struct {
	Items         []DealRecord `json:"items"`
	NextPageToken *string      `json:"next_page_token"`
}

func (response ListDeals200JSONResponse) VisitListDealsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDeals400Response struct {
}

func (response ListDeals400Response) VisitListDealsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ListDeals500Response struct {
}

func (response ListDeals500Response) VisitListDealsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type ListOrdersRequestObject struct {
	Params ListOrdersParams
}

type ListOrdersResponseObject interface {
	VisitListOrdersResponse(w http.ResponseWriter) error
}

type ListOrders200JSONResponse struct {
	Items         []OrderRecord `json:"items"`
	NextPageToken *string       `json:"next_page_token"`
}

func (response ListOrders200JSONResponse) VisitListOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListOrders400Response struct {
}

func (response ListOrders400Response) VisitListOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type ListOrders500Response struct {
}

func (response ListOrders500Response) VisitListOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type StreamOrdersRequestObject struct {
	Params StreamOrdersParams
}

type StreamOrdersResponseObject interface {
	VisitStreamOrdersResponse(w http.ResponseWriter) error
}

type StreamOrders200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamOrders200TexteventStreamResponse) VisitStreamOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type StreamOrders400Response struct {
}

func (response StreamOrders400Response) VisitStreamOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type StreamOrders500Response struct {
}

func (response StreamOrders500Response) VisitStreamOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List cached 3Commas bots
	// (GET /api/bots)
	ListBots(ctx context.Context, request ListBotsRequestObject) (ListBotsResponseObject, error)
	// List cached 3Commas deals
	// (GET /api/deals)
	ListDeals(ctx context.Context, request ListDealsRequestObject) (ListDealsResponseObject, error)
	// List acted-on bot events with Hyperliquid context
	// (GET /api/orders)
	ListOrders(ctx context.Context, request ListOrdersRequestObject) (ListOrdersResponseObject, error)
	// Stream live changes to acted-on orders
	// (GET /sse/orders)
	StreamOrders(ctx context.Context, request StreamOrdersRequestObject) (StreamOrdersResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBots operation middleware
func (sh *strictHandler) ListBots(w http.ResponseWriter, r *http.Request, params ListBotsParams) {
	var request ListBotsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBots(ctx, request.(ListBotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBots")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBotsResponseObject); ok {
		if err := validResponse.VisitListBotsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDeals operation middleware
func (sh *strictHandler) ListDeals(w http.ResponseWriter, r *http.Request, params ListDealsParams) {
	var request ListDealsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDeals(ctx, request.(ListDealsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDeals")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDealsResponseObject); ok {
		if err := validResponse.VisitListDealsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOrders operation middleware
func (sh *strictHandler) ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams) {
	var request ListOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOrders(ctx, request.(ListOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOrdersResponseObject); ok {
		if err := validResponse.VisitListOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamOrders operation middleware
func (sh *strictHandler) StreamOrders(w http.ResponseWriter, r *http.Request, params StreamOrdersParams) {
	var request StreamOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamOrders(ctx, request.(StreamOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamOrdersResponseObject); ok {
		if err := validResponse.VisitStreamOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
